// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/cook/live/[share_slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cook/live/[share_slug]">> = Specific
  const handler = {} as typeof import("../../app/cook/live/[share_slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import">> = Specific
  const handler = {} as typeof import("../../app/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my-recipes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-recipes">> = Specific
  const handler = {} as typeof import("../../app/my-recipes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new-recipe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-recipe">> = Specific
  const handler = {} as typeof import("../../app/new-recipe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preferences">> = Specific
  const handler = {} as typeof import("../../app/preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/[id]/new-version/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/new-version">> = Specific
  const handler = {} as typeof import("../../app/recipes/[id]/new-version/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]">> = Specific
  const handler = {} as typeof import("../../app/recipes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/[id]/versions/[versionId]/cook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/[versionId]/cook">> = Specific
  const handler = {} as typeof import("../../app/recipes/[id]/versions/[versionId]/cook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/[id]/versions/[versionId]/grocery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/[versionId]/grocery">> = Specific
  const handler = {} as typeof import("../../app/recipes/[id]/versions/[versionId]/grocery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/[id]/versions/[versionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../app/recipes/[id]/versions/[versionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/[id]/versions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/new">> = Specific
  const handler = {} as typeof import("../../app/recipes/[id]/versions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/new/from-text/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/new/from-text">> = Specific
  const handler = {} as typeof import("../../app/recipes/new/from-text/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recipes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/new">> = Specific
  const handler = {} as typeof import("../../app/recipes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../app/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/chef-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chef-chat">> = Specific
  const handler = {} as typeof import("../../app/api/ai/chef-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recipes/[id]/versions/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../app/api/recipes/[id]/versions/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
