import type { IngredientCatalogEntry } from "./ingredientResolutionTypes";

export type IngredientFamily = {
  id: string;
  label: string;
};

export const INGREDIENT_FAMILIES: Record<string, IngredientFamily> = {
  bean: { id: "fam_bean", label: "beans" },
  legume: { id: "fam_legume", label: "legumes" },
  herb: { id: "fam_herb", label: "herbs" },
  allium: { id: "fam_allium", label: "alliums" },
  leafy_green: { id: "fam_leafy_green", label: "leafy greens" },
  pepper: { id: "fam_pepper", label: "peppers" },
  mushroom: { id: "fam_mushroom", label: "mushrooms" },
  citrus: { id: "fam_citrus", label: "citrus" },
  dairy: { id: "fam_dairy", label: "dairy" },
  cheese: { id: "fam_cheese", label: "cheese" },
  protein: { id: "fam_protein", label: "protein" },
  seafood: { id: "fam_seafood", label: "seafood" },
  shellfish: { id: "fam_shellfish", label: "shellfish" },
  grain: { id: "fam_grain", label: "grains" },
  starch: { id: "fam_starch", label: "starches" },
  nut: { id: "fam_nut", label: "nuts" },
  seed: { id: "fam_seed", label: "seeds" },
};

export const INGREDIENT_CATALOG: IngredientCatalogEntry[] = [
  // --- Beans / Legumes ---
  {
    canonical_id: "ing_white_bean",
    canonical_key: "white_bean",
    display_label: "white beans",
    family_id: "fam_bean",
    family_key: "bean",
    aliases: [
      "white bean",
      "white beans",
      "cannellini bean",
      "cannellini beans",
      "great northern bean",
      "great northern beans",
      "navy bean",
      "navy beans",
      "haricot bean",
      "haricot beans",
      "cannellini",
    ],
  },
  {
    canonical_id: "ing_chickpea",
    canonical_key: "chickpea",
    display_label: "chickpeas",
    family_id: "fam_bean",
    family_key: "bean",
    aliases: [
      "chickpea",
      "chickpeas",
      "garbanzo bean",
      "garbanzo beans",
      "garbanzo",
      "garbanzos",
      "ceci bean",
      "ceci beans",
    ],
  },
  {
    canonical_id: "ing_black_bean",
    canonical_key: "black_bean",
    display_label: "black beans",
    family_id: "fam_bean",
    family_key: "bean",
    aliases: ["black bean", "black beans", "turtle bean", "turtle beans"],
  },
  {
    canonical_id: "ing_lentil",
    canonical_key: "lentil",
    display_label: "lentils",
    family_id: "fam_legume",
    family_key: "legume",
    aliases: [
      "lentil",
      "lentils",
      "green lentil",
      "green lentils",
      "red lentil",
      "red lentils",
      "brown lentil",
      "brown lentils",
      "french lentil",
      "french lentils",
      "beluga lentil",
      "beluga lentils",
      "black lentil",
      "black lentils",
      "puy lentil",
      "puy lentils",
    ],
  },
  {
    canonical_id: "ing_kidney_bean",
    canonical_key: "kidney_bean",
    display_label: "kidney beans",
    family_id: "fam_bean",
    family_key: "bean",
    aliases: ["kidney bean", "kidney beans", "red kidney bean", "red kidney beans"],
  },
  {
    canonical_id: "ing_pinto_bean",
    canonical_key: "pinto_bean",
    display_label: "pinto beans",
    family_id: "fam_bean",
    family_key: "bean",
    aliases: ["pinto bean", "pinto beans"],
  },
  {
    canonical_id: "ing_edamame",
    canonical_key: "edamame",
    display_label: "edamame",
    family_id: "fam_legume",
    family_key: "legume",
    aliases: ["edamame", "soybeans", "soybean", "fresh soybeans"],
  },
  {
    canonical_id: "ing_broad_bean",
    canonical_key: "broad_bean",
    display_label: "fava beans",
    family_id: "fam_bean",
    family_key: "bean",
    aliases: ["fava bean", "fava beans", "broad bean", "broad beans"],
  },

  // --- Herbs ---
  {
    canonical_id: "ing_basil",
    canonical_key: "basil",
    display_label: "basil",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: [
      "basil",
      "sweet basil",
      "genovese basil",
      "italian basil",
      "fresh basil",
    ],
    blockers: ["thai basil"],
  },
  {
    canonical_id: "ing_thai_basil",
    canonical_key: "thai_basil",
    display_label: "Thai basil",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["thai basil", "asian basil"],
  },
  {
    canonical_id: "ing_cilantro",
    canonical_key: "cilantro",
    display_label: "cilantro",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: [
      "cilantro",
      "coriander leaves",
      "coriander leaf",
      "fresh coriander",
      "chinese parsley",
    ],
  },
  {
    canonical_id: "ing_parsley",
    canonical_key: "parsley",
    display_label: "parsley",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: [
      "parsley",
      "flat-leaf parsley",
      "flat leaf parsley",
      "italian parsley",
      "curly parsley",
      "fresh parsley",
    ],
  },
  {
    canonical_id: "ing_thyme",
    canonical_key: "thyme",
    display_label: "thyme",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["thyme", "fresh thyme", "dried thyme"],
  },
  {
    canonical_id: "ing_oregano",
    canonical_key: "oregano",
    display_label: "oregano",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["oregano", "fresh oregano", "dried oregano", "mexican oregano"],
  },
  {
    canonical_id: "ing_rosemary",
    canonical_key: "rosemary",
    display_label: "rosemary",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["rosemary", "fresh rosemary", "dried rosemary"],
  },
  {
    canonical_id: "ing_sage",
    canonical_key: "sage",
    display_label: "sage",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["sage", "fresh sage", "dried sage"],
  },
  {
    canonical_id: "ing_mint",
    canonical_key: "mint",
    display_label: "mint",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["mint", "fresh mint", "spearmint", "peppermint"],
  },
  {
    canonical_id: "ing_dill",
    canonical_key: "dill",
    display_label: "dill",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["dill", "fresh dill", "dill weed"],
  },
  {
    canonical_id: "ing_chives",
    canonical_key: "chives",
    display_label: "chives",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["chive", "chives", "fresh chives"],
  },
  {
    canonical_id: "ing_tarragon",
    canonical_key: "tarragon",
    display_label: "tarragon",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["tarragon", "french tarragon", "fresh tarragon"],
  },
  {
    canonical_id: "ing_bay_leaf",
    canonical_key: "bay_leaf",
    display_label: "bay leaves",
    family_id: "fam_herb",
    family_key: "herb",
    aliases: ["bay leaf", "bay leaves", "bay laurel", "dried bay leaf"],
  },

  // --- Alliums ---
  {
    canonical_id: "ing_onion",
    canonical_key: "onion",
    display_label: "onion",
    family_id: "fam_allium",
    family_key: "allium",
    aliases: [
      "onion",
      "onions",
      "yellow onion",
      "yellow onions",
      "white onion",
      "white onions",
      "brown onion",
      "brown onions",
    ],
    blockers: ["red onion", "green onion", "spring onion", "scallion"],
  },
  {
    canonical_id: "ing_red_onion",
    canonical_key: "red_onion",
    display_label: "red onion",
    family_id: "fam_allium",
    family_key: "allium",
    aliases: ["red onion", "red onions", "purple onion", "purple onions"],
  },
  {
    canonical_id: "ing_scallion",
    canonical_key: "scallion",
    display_label: "scallions",
    family_id: "fam_allium",
    family_key: "allium",
    aliases: [
      "scallion",
      "scallions",
      "green onion",
      "green onions",
      "spring onion",
      "spring onions",
    ],
  },
  {
    canonical_id: "ing_shallot",
    canonical_key: "shallot",
    display_label: "shallots",
    family_id: "fam_allium",
    family_key: "allium",
    aliases: ["shallot", "shallots", "french shallot", "banana shallot"],
  },
  {
    canonical_id: "ing_leek",
    canonical_key: "leek",
    display_label: "leeks",
    family_id: "fam_allium",
    family_key: "allium",
    aliases: ["leek", "leeks"],
  },
  {
    canonical_id: "ing_garlic",
    canonical_key: "garlic",
    display_label: "garlic",
    family_id: "fam_allium",
    family_key: "allium",
    aliases: ["garlic", "garlic clove", "garlic cloves", "fresh garlic", "minced garlic", "garlic bulb"],
  },

  // --- Leafy Greens ---
  {
    canonical_id: "ing_spinach",
    canonical_key: "spinach",
    display_label: "spinach",
    family_id: "fam_leafy_green",
    family_key: "leafy_green",
    aliases: ["spinach", "baby spinach", "fresh spinach"],
  },
  {
    canonical_id: "ing_kale",
    canonical_key: "kale",
    display_label: "kale",
    family_id: "fam_leafy_green",
    family_key: "leafy_green",
    aliases: [
      "kale",
      "curly kale",
      "lacinato kale",
      "dinosaur kale",
      "tuscan kale",
      "cavolo nero",
      "black kale",
    ],
  },
  {
    canonical_id: "ing_arugula",
    canonical_key: "arugula",
    display_label: "arugula",
    family_id: "fam_leafy_green",
    family_key: "leafy_green",
    aliases: ["arugula", "rocket", "wild rocket", "baby arugula"],
  },
  {
    canonical_id: "ing_chard",
    canonical_key: "chard",
    display_label: "chard",
    family_id: "fam_leafy_green",
    family_key: "leafy_green",
    aliases: [
      "chard",
      "swiss chard",
      "rainbow chard",
      "silverbeet",
      "silver beet",
      "red chard",
    ],
  },
  {
    canonical_id: "ing_collard_greens",
    canonical_key: "collard_greens",
    display_label: "collard greens",
    family_id: "fam_leafy_green",
    family_key: "leafy_green",
    aliases: ["collard greens", "collard green", "collards"],
  },
  {
    canonical_id: "ing_romaine",
    canonical_key: "romaine",
    display_label: "romaine",
    family_id: "fam_leafy_green",
    family_key: "leafy_green",
    aliases: ["romaine", "romaine lettuce", "cos lettuce", "cos"],
  },

  // --- Peppers ---
  {
    canonical_id: "ing_bell_pepper",
    canonical_key: "bell_pepper",
    display_label: "bell peppers",
    family_id: "fam_pepper",
    family_key: "pepper",
    aliases: [
      "bell pepper",
      "bell peppers",
      "sweet pepper",
      "sweet peppers",
      "capsicum",
      "red bell pepper",
      "green bell pepper",
      "yellow bell pepper",
      "orange bell pepper",
    ],
  },
  {
    canonical_id: "ing_jalapeño",
    canonical_key: "jalapeño",
    display_label: "jalapeños",
    family_id: "fam_pepper",
    family_key: "pepper",
    aliases: [
      "jalapeño",
      "jalapeños",
      "jalapeno",
      "jalapenos",
      "jalapeño pepper",
      "jalapeño peppers",
    ],
  },
  {
    canonical_id: "ing_serrano",
    canonical_key: "serrano",
    display_label: "serrano peppers",
    family_id: "fam_pepper",
    family_key: "pepper",
    aliases: ["serrano", "serrano pepper", "serrano peppers", "serrano chile", "serrano chiles"],
  },
  {
    canonical_id: "ing_chipotle",
    canonical_key: "chipotle",
    display_label: "chipotle",
    family_id: "fam_pepper",
    family_key: "pepper",
    aliases: [
      "chipotle",
      "chipotle pepper",
      "chipotle peppers",
      "chipotles in adobo",
      "chipotle in adobo",
      "smoked jalapeño",
    ],
  },
  {
    canonical_id: "ing_red_pepper_flakes",
    canonical_key: "red_pepper_flakes",
    display_label: "red pepper flakes",
    family_id: "fam_pepper",
    family_key: "pepper",
    aliases: [
      "red pepper flakes",
      "crushed red pepper",
      "chili flakes",
      "pepper flakes",
      "crushed chili flakes",
    ],
  },
  {
    canonical_id: "ing_ancho",
    canonical_key: "ancho",
    display_label: "ancho chiles",
    family_id: "fam_pepper",
    family_key: "pepper",
    aliases: ["ancho", "ancho chile", "ancho chiles", "dried ancho", "ancho chili"],
  },

  // --- Mushrooms ---
  {
    canonical_id: "ing_mushroom",
    canonical_key: "mushroom",
    display_label: "mushrooms",
    family_id: "fam_mushroom",
    family_key: "mushroom",
    aliases: [
      "mushroom",
      "mushrooms",
      "button mushroom",
      "button mushrooms",
      "cremini mushroom",
      "cremini mushrooms",
      "crimini mushroom",
      "crimini mushrooms",
      "white mushroom",
      "white mushrooms",
      "baby bella",
    ],
    blockers: ["shiitake", "portobello", "oyster mushroom", "porcini", "chanterelle"],
  },
  {
    canonical_id: "ing_shiitake",
    canonical_key: "shiitake",
    display_label: "shiitake mushrooms",
    family_id: "fam_mushroom",
    family_key: "mushroom",
    aliases: ["shiitake", "shiitake mushroom", "shiitake mushrooms", "dried shiitake"],
  },
  {
    canonical_id: "ing_portobello",
    canonical_key: "portobello",
    display_label: "portobello mushrooms",
    family_id: "fam_mushroom",
    family_key: "mushroom",
    aliases: ["portobello", "portobello mushroom", "portobello mushrooms", "portabello", "portabella"],
  },
  {
    canonical_id: "ing_oyster_mushroom",
    canonical_key: "oyster_mushroom",
    display_label: "oyster mushrooms",
    family_id: "fam_mushroom",
    family_key: "mushroom",
    aliases: ["oyster mushroom", "oyster mushrooms", "king oyster mushroom"],
  },
  {
    canonical_id: "ing_porcini",
    canonical_key: "porcini",
    display_label: "porcini mushrooms",
    family_id: "fam_mushroom",
    family_key: "mushroom",
    aliases: ["porcini", "porcini mushroom", "porcini mushrooms", "dried porcini", "cep", "ceps"],
  },

  // --- Citrus ---
  {
    canonical_id: "ing_lemon",
    canonical_key: "lemon",
    display_label: "lemon",
    family_id: "fam_citrus",
    family_key: "citrus",
    aliases: ["lemon", "lemons", "lemon juice", "lemon zest", "fresh lemon"],
  },
  {
    canonical_id: "ing_lime",
    canonical_key: "lime",
    display_label: "lime",
    family_id: "fam_citrus",
    family_key: "citrus",
    aliases: ["lime", "limes", "lime juice", "lime zest", "fresh lime"],
  },
  {
    canonical_id: "ing_orange",
    canonical_key: "orange",
    display_label: "orange",
    family_id: "fam_citrus",
    family_key: "citrus",
    aliases: ["orange", "oranges", "orange juice", "orange zest", "blood orange", "navel orange"],
  },

  // --- Dairy & Cheese ---
  {
    canonical_id: "ing_parmesan",
    canonical_key: "parmesan",
    display_label: "parmesan",
    family_id: "fam_cheese",
    family_key: "cheese",
    aliases: [
      "parmesan",
      "parmigiano",
      "parmigiano reggiano",
      "parmigiano-reggiano",
      "parmesan cheese",
      "parm",
      "grana padano",
    ],
  },
  {
    canonical_id: "ing_pecorino",
    canonical_key: "pecorino",
    display_label: "pecorino",
    family_id: "fam_cheese",
    family_key: "cheese",
    aliases: [
      "pecorino",
      "pecorino romano",
      "pecorino sardo",
      "pecorino cheese",
    ],
  },
  {
    canonical_id: "ing_mozzarella",
    canonical_key: "mozzarella",
    display_label: "mozzarella",
    family_id: "fam_cheese",
    family_key: "cheese",
    aliases: [
      "mozzarella",
      "fresh mozzarella",
      "buffalo mozzarella",
      "burrata",
      "fior di latte",
    ],
  },
  {
    canonical_id: "ing_ricotta",
    canonical_key: "ricotta",
    display_label: "ricotta",
    family_id: "fam_cheese",
    family_key: "cheese",
    aliases: ["ricotta", "ricotta cheese", "fresh ricotta"],
  },
  {
    canonical_id: "ing_feta",
    canonical_key: "feta",
    display_label: "feta",
    family_id: "fam_cheese",
    family_key: "cheese",
    aliases: ["feta", "feta cheese", "greek feta"],
  },
  {
    canonical_id: "ing_cheddar",
    canonical_key: "cheddar",
    display_label: "cheddar",
    family_id: "fam_cheese",
    family_key: "cheese",
    aliases: ["cheddar", "cheddar cheese", "sharp cheddar", "mild cheddar", "aged cheddar"],
  },
  {
    canonical_id: "ing_cream_cheese",
    canonical_key: "cream_cheese",
    display_label: "cream cheese",
    family_id: "fam_dairy",
    family_key: "dairy",
    aliases: ["cream cheese", "creamed cheese"],
  },
  {
    canonical_id: "ing_greek_yogurt",
    canonical_key: "greek_yogurt",
    display_label: "Greek yogurt",
    family_id: "fam_dairy",
    family_key: "dairy",
    aliases: ["greek yogurt", "greek yoghurt", "strained yogurt", "labneh"],
  },
  {
    canonical_id: "ing_heavy_cream",
    canonical_key: "heavy_cream",
    display_label: "heavy cream",
    family_id: "fam_dairy",
    family_key: "dairy",
    aliases: [
      "heavy cream",
      "heavy whipping cream",
      "double cream",
      "whipping cream",
      "thickened cream",
    ],
  },
  {
    canonical_id: "ing_butter",
    canonical_key: "butter",
    display_label: "butter",
    family_id: "fam_dairy",
    family_key: "dairy",
    aliases: ["butter", "unsalted butter", "salted butter", "clarified butter", "ghee"],
  },
  {
    canonical_id: "ing_sour_cream",
    canonical_key: "sour_cream",
    display_label: "sour cream",
    family_id: "fam_dairy",
    family_key: "dairy",
    aliases: ["sour cream", "creme fraiche", "crème fraîche", "cultured cream"],
  },

  // --- Proteins ---
  {
    canonical_id: "ing_chicken",
    canonical_key: "chicken",
    display_label: "chicken",
    family_id: "fam_protein",
    family_key: "protein",
    aliases: [
      "chicken",
      "chicken breast",
      "chicken breasts",
      "chicken thigh",
      "chicken thighs",
      "chicken drumstick",
      "chicken drumsticks",
      "chicken wings",
      "whole chicken",
      "rotisserie chicken",
      "boneless chicken",
      "bone-in chicken",
    ],
  },
  {
    canonical_id: "ing_beef",
    canonical_key: "beef",
    display_label: "beef",
    family_id: "fam_protein",
    family_key: "protein",
    aliases: [
      "beef",
      "ground beef",
      "beef chuck",
      "chuck roast",
      "beef sirloin",
      "sirloin",
      "flank steak",
      "ribeye",
      "short ribs",
      "beef brisket",
    ],
  },
  {
    canonical_id: "ing_pork",
    canonical_key: "pork",
    display_label: "pork",
    family_id: "fam_protein",
    family_key: "protein",
    aliases: [
      "pork",
      "pork loin",
      "pork belly",
      "pork shoulder",
      "pork chops",
      "pork tenderloin",
      "ground pork",
    ],
  },
  {
    canonical_id: "ing_lamb",
    canonical_key: "lamb",
    display_label: "lamb",
    family_id: "fam_protein",
    family_key: "protein",
    aliases: ["lamb", "ground lamb", "lamb chops", "lamb shoulder", "lamb leg", "rack of lamb"],
  },
  {
    canonical_id: "ing_tofu",
    canonical_key: "tofu",
    display_label: "tofu",
    family_id: "fam_protein",
    family_key: "protein",
    aliases: [
      "tofu",
      "silken tofu",
      "soft tofu",
      "firm tofu",
      "extra-firm tofu",
      "extra firm tofu",
    ],
  },
  {
    canonical_id: "ing_tempeh",
    canonical_key: "tempeh",
    display_label: "tempeh",
    family_id: "fam_protein",
    family_key: "protein",
    aliases: ["tempeh"],
  },
  {
    canonical_id: "ing_egg",
    canonical_key: "egg",
    display_label: "eggs",
    family_id: "fam_protein",
    family_key: "protein",
    aliases: ["egg", "eggs", "large eggs", "whole eggs", "egg yolk", "egg white"],
  },

  // --- Seafood ---
  {
    canonical_id: "ing_shrimp",
    canonical_key: "shrimp",
    display_label: "shrimp",
    family_id: "fam_shellfish",
    family_key: "shellfish",
    aliases: ["shrimp", "prawns", "prawn", "large shrimp", "jumbo shrimp", "tiger prawns"],
  },
  {
    canonical_id: "ing_salmon",
    canonical_key: "salmon",
    display_label: "salmon",
    family_id: "fam_seafood",
    family_key: "seafood",
    aliases: [
      "salmon",
      "salmon fillet",
      "salmon fillets",
      "atlantic salmon",
      "sockeye salmon",
      "smoked salmon",
      "coho salmon",
    ],
  },
  {
    canonical_id: "ing_cod",
    canonical_key: "cod",
    display_label: "cod",
    family_id: "fam_seafood",
    family_key: "seafood",
    aliases: ["cod", "cod fillet", "cod fillets", "atlantic cod", "pacific cod"],
  },
  {
    canonical_id: "ing_tuna",
    canonical_key: "tuna",
    display_label: "tuna",
    family_id: "fam_seafood",
    family_key: "seafood",
    aliases: ["tuna", "canned tuna", "tuna steak", "albacore tuna", "yellowfin tuna"],
  },

  // --- Grains & Starches ---
  {
    canonical_id: "ing_pasta",
    canonical_key: "pasta",
    display_label: "pasta",
    family_id: "fam_starch",
    family_key: "starch",
    aliases: [
      "pasta",
      "spaghetti",
      "rigatoni",
      "penne",
      "fettuccine",
      "linguine",
      "tagliatelle",
      "bucatini",
      "farfalle",
      "orecchiette",
      "fusilli",
      "pappardelle",
      "lasagne",
      "lasagna",
    ],
  },
  {
    canonical_id: "ing_rice",
    canonical_key: "rice",
    display_label: "rice",
    family_id: "fam_grain",
    family_key: "grain",
    aliases: [
      "rice",
      "white rice",
      "brown rice",
      "jasmine rice",
      "basmati rice",
      "arborio rice",
      "short-grain rice",
      "long-grain rice",
      "sushi rice",
    ],
  },
  {
    canonical_id: "ing_quinoa",
    canonical_key: "quinoa",
    display_label: "quinoa",
    family_id: "fam_grain",
    family_key: "grain",
    aliases: ["quinoa", "white quinoa", "red quinoa", "black quinoa", "tri-color quinoa"],
  },
  {
    canonical_id: "ing_potato",
    canonical_key: "potato",
    display_label: "potatoes",
    family_id: "fam_starch",
    family_key: "starch",
    aliases: [
      "potato",
      "potatoes",
      "yukon gold potato",
      "yukon gold potatoes",
      "russet potato",
      "russet potatoes",
      "red potato",
      "red potatoes",
      "fingerling potato",
      "fingerling potatoes",
      "baby potato",
      "baby potatoes",
      "new potato",
      "new potatoes",
    ],
    blockers: ["sweet potato"],
  },
  {
    canonical_id: "ing_sweet_potato",
    canonical_key: "sweet_potato",
    display_label: "sweet potatoes",
    family_id: "fam_starch",
    family_key: "starch",
    aliases: ["sweet potato", "sweet potatoes", "yam", "yams"],
  },
  {
    canonical_id: "ing_polenta",
    canonical_key: "polenta",
    display_label: "polenta",
    family_id: "fam_grain",
    family_key: "grain",
    aliases: ["polenta", "grits", "cornmeal", "coarse cornmeal"],
  },
  {
    canonical_id: "ing_couscous",
    canonical_key: "couscous",
    display_label: "couscous",
    family_id: "fam_grain",
    family_key: "grain",
    aliases: ["couscous", "israeli couscous", "pearl couscous", "whole wheat couscous"],
  },

  // --- Pantry staples ---
  {
    canonical_id: "ing_olive_oil",
    canonical_key: "olive_oil",
    display_label: "olive oil",
    family_id: null,
    family_key: null,
    aliases: ["olive oil", "extra virgin olive oil", "evoo", "virgin olive oil"],
  },
  {
    canonical_id: "ing_tomato",
    canonical_key: "tomato",
    display_label: "tomatoes",
    family_id: null,
    family_key: null,
    aliases: [
      "tomato",
      "tomatoes",
      "canned tomatoes",
      "crushed tomatoes",
      "whole peeled tomatoes",
      "san marzano tomatoes",
      "cherry tomatoes",
      "grape tomatoes",
      "plum tomatoes",
      "roma tomatoes",
      "heirloom tomatoes",
    ],
  },
  {
    canonical_id: "ing_soy_sauce",
    canonical_key: "soy_sauce",
    display_label: "soy sauce",
    family_id: null,
    family_key: null,
    aliases: ["soy sauce", "soya sauce", "dark soy sauce", "light soy sauce", "tamari", "low sodium soy sauce"],
  },
  {
    canonical_id: "ing_fish_sauce",
    canonical_key: "fish_sauce",
    display_label: "fish sauce",
    family_id: null,
    family_key: null,
    aliases: ["fish sauce", "nam pla", "nuoc mam"],
  },
  {
    canonical_id: "ing_tahini",
    canonical_key: "tahini",
    display_label: "tahini",
    family_id: null,
    family_key: null,
    aliases: ["tahini", "sesame paste", "tahina"],
  },
  {
    canonical_id: "ing_miso",
    canonical_key: "miso",
    display_label: "miso",
    family_id: null,
    family_key: null,
    aliases: ["miso", "miso paste", "white miso", "red miso", "shiro miso", "aka miso"],
  },

  // --- Nuts & Seeds ---
  {
    canonical_id: "ing_pine_nuts",
    canonical_key: "pine_nuts",
    display_label: "pine nuts",
    family_id: "fam_nut",
    family_key: "nut",
    aliases: ["pine nuts", "pine nut", "pignoli", "pignoli nuts", "toasted pine nuts"],
  },
  {
    canonical_id: "ing_almonds",
    canonical_key: "almonds",
    display_label: "almonds",
    family_id: "fam_nut",
    family_key: "nut",
    aliases: [
      "almond",
      "almonds",
      "sliced almonds",
      "blanched almonds",
      "slivered almonds",
      "toasted almonds",
    ],
  },
  {
    canonical_id: "ing_walnuts",
    canonical_key: "walnuts",
    display_label: "walnuts",
    family_id: "fam_nut",
    family_key: "nut",
    aliases: ["walnut", "walnuts", "toasted walnuts"],
  },
  {
    canonical_id: "ing_sesame_seeds",
    canonical_key: "sesame_seeds",
    display_label: "sesame seeds",
    family_id: "fam_seed",
    family_key: "seed",
    aliases: ["sesame seeds", "sesame seed", "toasted sesame seeds", "black sesame seeds", "white sesame seeds"],
  },
];

// -- Lookup indexes built at module load time --

function singularizeToken(token: string): string {
  if (token.length > 4 && token.endsWith("ies")) {
    return `${token.slice(0, -3)}y`;
  }
  if (token.length > 4 && token.endsWith("es")) {
    return token.slice(0, -2);
  }
  if (token.length > 3 && token.endsWith("s")) {
    return token.slice(0, -1);
  }
  return token;
}

function normalizeAliasKey(alias: string): string {
  return alias
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s-]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim()
    .split(/\s+/)
    .map(singularizeToken)
    .join(" ");
}

// Maps normalized alias → catalog entry
export const ALIAS_TO_ENTRY: Map<string, IngredientCatalogEntry> = new Map(
  INGREDIENT_CATALOG.flatMap((entry) =>
    entry.aliases.map((alias) => [normalizeAliasKey(alias), entry] as const)
  )
);

// Maps canonical_key → catalog entry
export const CANONICAL_KEY_TO_ENTRY: Map<string, IngredientCatalogEntry> = new Map(
  INGREDIENT_CATALOG.map((entry) => [entry.canonical_key, entry])
);

// Maps family_key → entries belonging to that family
export const FAMILY_KEY_TO_ENTRIES: Map<string, IngredientCatalogEntry[]> = new Map();
for (const entry of INGREDIENT_CATALOG) {
  if (entry.family_key) {
    const existing = FAMILY_KEY_TO_ENTRIES.get(entry.family_key) ?? [];
    existing.push(entry);
    FAMILY_KEY_TO_ENTRIES.set(entry.family_key, existing);
  }
}

export { normalizeAliasKey };
