import type { MacroTargets } from "./macroTargetValidator";

// ── Suite names ───────────────────────────────────────────────────────────────

export type BenchmarkSuiteName =
  | "smoke"
  | "core"
  | "full"
  | "stress"
  | "baseline"
  | "dietary"
  | "macro"
  | "reject"
  | "messy";

/** Benchmark grouping for pass-rate reporting and acceptance criteria. */
export type BenchmarkCategory =
  | "baseline"   // standard feasible cases, no special constraints
  | "dietary"    // feasible but with active dietary constraints
  | "macro"      // feasible with macro targets
  | "reject"     // should fail — system must reject these (structurally infeasible)
  | "messy";     // real-world ambiguous prompts — tests robustness

export type RecipeBenchmarkCase = {
  id: string;
  prompt: string;
  titleHint?: string | null;
  dishHint?: string | null;
  dietaryConstraints?: string[];
  availableIngredients?: string[];
  preferredIngredients?: string[];
  forbiddenIngredients?: string[];
  macroTargets?: MacroTargets | null;
  servings?: number | null;

  /** Expectations */
  expectedDishFamily: string;
  mustHaveClasses?: string[];
  mustNotHaveClasses?: string[];
  shouldPass?: boolean;

  /** Benchmark grouping for pass-rate reporting */
  category?: BenchmarkCategory;
};

// ── Suite definitions ─────────────────────────────────────────────────────────
//
// "full"   = undefined (all cases)
// "stress" = known flaky/slow cases for instability debugging
// "smoke"  = fast sanity check, one per major family
// "core"   = representative regression set, ~30 cases
//
// Category suites (baseline/dietary/macro/reject/messy) are filtered dynamically
// from RECIPE_BENCHMARK_CASES by category field.

export const BENCHMARK_SUITE_CASE_IDS: Partial<Record<BenchmarkSuiteName, string[]>> = {
  smoke: [
    // baseline — one per major family
    "flan_classic_01",
    "brownie_01",
    "risotto_01",
    "stir_fry_01",
    "pizza_01",
    "soup_01",
    "omelet_01",
    "tacos_01",
    // dietary
    "vegan_curry_01",
    "gluten_free_pancake_01",
    // macro
    "pasta_high_protein_01",
    "macro_highprotein_stirfry_01",
    // reject
    "impossible_dessert_macro_01",
    // messy
    "messy_pantry_01",
    "messy_ambiguous_01",
    "messy_goal_01",
  ],
  core: [
    // baseline (15)
    "flan_classic_01", "flan_coffee_02",
    "brownie_01", "cookie_01", "cheesecake_01",
    "risotto_01", "stir_fry_01", "fried_rice_01", "curry_01", "pasta_high_protein_01",
    "soup_01", "omelet_01", "tacos_01", "pizza_01", "sandwich_01",
    // dietary (5)
    "vegan_curry_01", "gluten_free_pancake_01",
    "dietary_dairyfree_pasta_01", "dietary_vegan_tacos_01", "dietary_vegan_soup_01",
    // macro (5)
    "pasta_high_protein_01", "macro_highprotein_stirfry_01",
    "macro_lowcalorie_soup_01", "macro_highprotein_curry_01", "macro_lowcarb_salad_01",
    // reject (all 5)
    "impossible_dessert_macro_01", "reject_brownie_highprotein_lowcal_01",
    "reject_smoothie_highprotein_lowcal_01", "reject_cookie_lowcal_01", "reject_pasta_lowcarb_01",
    // messy (5 original)
    "messy_pantry_01", "messy_health_01", "messy_fast_01", "messy_combo_01", "messy_ambiguous_01",
  ],
  stress: [
    // Cases with observed instability or routing failures — for dedicated flaky investigation
    "flan_classic_01",       // sometimes regenerate_from_ingredients
    "pizza_01",              // sometimes regenerate_from_ingredients
    "brownie_high_protein_02", // sometimes regenerate_from_ingredients
    "curry_01",              // sometimes needs planner retry
    "vegan_curry_01",        // sometimes needs planner retry
    "messy_pantry_04",       // family:null (resolver signal gap)
    "messy_pantry_07",       // family:null (resolver signal gap)
    "messy_pantry_09",       // family:null (resolver signal gap)
    "messy_conflict_06",     // family:null (dessert routing)
    "messy_conflict_03",     // borderline macro feasibility
  ],
};

export const RECIPE_BENCHMARK_CASES: RecipeBenchmarkCase[] = [
  {
    id: "flan_classic_01",
    prompt: "Make a classic vanilla flan for 6 people.",
    titleHint: "Classic Vanilla Flan",
    dishHint: "flan",
    servings: 6,
    expectedDishFamily: "custard_flan",
    mustHaveClasses: ["egg", "dairy", "sweetener"],
    mustNotHaveClasses: ["allium", "protein_meat", "flour_grain", "starch"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "flan_coffee_02",
    prompt: "Make a coffee flan for 6 with a smooth texture.",
    titleHint: "Coffee Flan",
    dishHint: "flan",
    servings: 6,
    expectedDishFamily: "custard_flan",
    mustHaveClasses: ["egg", "dairy", "sweetener"],
    mustNotHaveClasses: ["allium", "vegetable_root", "soy_sauce"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "brownie_01",
    prompt: "Make fudgy brownies for 9 squares.",
    titleHint: "Fudgy Brownies",
    dishHint: "brownie",
    servings: 9,
    expectedDishFamily: "brownie",
    mustHaveClasses: ["cocoa_or_chocolate", "fat_oil", "sweetener"],
    mustNotHaveClasses: ["allium", "protein_meat", "broth"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "brownie_high_protein_02",
    prompt: "Make brownies with higher protein but still like real brownies.",
    titleHint: "Higher Protein Brownies",
    dishHint: "brownie",
    macroTargets: { proteinMinG: 10, caloriesMax: 280 },
    servings: 9,
    expectedDishFamily: "brownie",
    mustHaveClasses: ["cocoa_or_chocolate", "sweetener"],
    mustNotHaveClasses: ["allium", "broth"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "cookie_01",
    prompt: "Make chewy chocolate chip cookies.",
    titleHint: "Chewy Chocolate Chip Cookies",
    dishHint: "cookie",
    servings: 12,
    expectedDishFamily: "cookie",
    mustHaveClasses: ["flour_grain", "fat_oil", "sweetener"],
    mustNotHaveClasses: ["allium", "soy_sauce"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "cheesecake_01",
    prompt: "Make a baked cheesecake for 8.",
    titleHint: "Baked Cheesecake",
    dishHint: "cheesecake",
    servings: 8,
    expectedDishFamily: "cheesecake",
    mustHaveClasses: ["dairy", "sweetener"],
    mustNotHaveClasses: ["allium", "protein_meat", "soy_sauce"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "muffin_01",
    prompt: "Make blueberry muffins for breakfast.",
    titleHint: "Blueberry Muffins",
    dishHint: "muffin",
    servings: 12,
    expectedDishFamily: "muffin_quick_bread",
    mustHaveClasses: ["flour_grain", "leavening"],
    mustNotHaveClasses: ["allium", "protein_fish"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "pancake_01",
    prompt: "Make fluffy pancakes for 4.",
    titleHint: "Fluffy Pancakes",
    dishHint: "pancake",
    servings: 4,
    expectedDishFamily: "pancake_waffle",
    mustHaveClasses: ["flour_grain"],
    mustNotHaveClasses: ["allium", "protein_fish", "soy_sauce"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "risotto_01",
    prompt: "Make mushroom risotto for dinner.",
    titleHint: "Mushroom Risotto",
    dishHint: "risotto",
    servings: 4,
    expectedDishFamily: "risotto",
    mustHaveClasses: ["starch", "liquid_base", "fat_oil"],
    mustNotHaveClasses: ["sweetener", "cocoa_or_chocolate", "leavening"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "stir_fry_01",
    prompt: "Make a chicken stir fry with vegetables for 4.",
    titleHint: "Chicken Stir Fry",
    dishHint: "stir fry",
    servings: 4,
    expectedDishFamily: "stir_fry",
    mustHaveClasses: ["fat_oil"],
    mustNotHaveClasses: ["leavening", "custard_base", "icing"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "fried_rice_01",
    prompt: "Make egg fried rice for 3.",
    titleHint: "Egg Fried Rice",
    dishHint: "fried rice",
    servings: 3,
    expectedDishFamily: "fried_rice",
    mustHaveClasses: ["starch", "fat_oil"],
    mustNotHaveClasses: ["custard_base", "icing", "cocoa_or_chocolate"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "curry_01",
    prompt: "Make a chicken curry with a rich sauce for 4.",
    titleHint: "Chicken Curry",
    dishHint: "curry",
    servings: 4,
    expectedDishFamily: "curry",
    mustHaveClasses: ["fat_oil"],
    mustNotHaveClasses: ["icing", "custard_base", "leavening"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "pasta_high_protein_01",
    prompt: "Make a high-protein creamy pasta under 550 calories per serving.",
    titleHint: "High Protein Creamy Pasta",
    dishHint: "pasta",
    macroTargets: { caloriesMax: 550, proteinMinG: 30 },
    servings: 4,
    expectedDishFamily: "pasta",
    mustHaveClasses: ["starch"],
    mustNotHaveClasses: ["leavening", "custard_base", "icing"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "soup_01",
    prompt: "Make a vegetable soup for 5.",
    titleHint: "Vegetable Soup",
    dishHint: "soup",
    servings: 5,
    expectedDishFamily: "soup_stew",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["leavening", "icing", "custard_base"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "smoothie_high_protein_01",
    prompt: "Make a high-protein berry smoothie under 350 calories.",
    titleHint: "High Protein Berry Smoothie",
    dishHint: "smoothie",
    servings: 2,
    macroTargets: { caloriesMax: 350, proteinMinG: 20 },
    expectedDishFamily: "smoothie",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["allium", "protein_meat", "broth"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "salad_01",
    prompt: "Make a hearty salad for lunch with a proper dressing.",
    titleHint: "Hearty Lunch Salad",
    dishHint: "salad",
    servings: 2,
    expectedDishFamily: "salad",
    mustHaveClasses: [],
    mustNotHaveClasses: ["leavening", "cocoa_or_chocolate", "custard_base"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "omelet_01",
    prompt: "Make a mushroom omelet for breakfast.",
    titleHint: "Mushroom Omelet",
    dishHint: "omelet",
    servings: 1,
    expectedDishFamily: "omelet_frittata",
    mustHaveClasses: ["egg", "fat_oil"],
    mustNotHaveClasses: ["cocoa_or_chocolate", "icing", "custard_base"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "tacos_01",
    prompt: "Make chicken tacos for dinner.",
    titleHint: "Chicken Tacos",
    dishHint: "tacos",
    servings: 4,
    expectedDishFamily: "tacos",
    mustHaveClasses: [],
    mustNotHaveClasses: ["custard_base", "icing", "cocoa_or_chocolate"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "pizza_01",
    prompt: "Make a homemade margherita pizza.",
    titleHint: "Margherita Pizza",
    dishHint: "pizza",
    servings: 4,
    expectedDishFamily: "pizza_flatbread",
    mustHaveClasses: ["flour_grain"],
    mustNotHaveClasses: ["custard_base", "icing", "broth"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "sandwich_01",
    prompt: "Make a grilled chicken sandwich.",
    titleHint: "Grilled Chicken Sandwich",
    dishHint: "sandwich",
    servings: 2,
    expectedDishFamily: "sandwich_wrap",
    mustHaveClasses: ["flour_grain"],
    mustNotHaveClasses: ["custard_base", "icing", "broth"],
    shouldPass: true,
    category: "baseline",
  },

  // ── Edge cases ───────────────────────────────────────────────────────────────

  {
    id: "vegan_curry_01",
    prompt: "Make a vegan curry with strong flavor and good protein.",
    titleHint: "Vegan Protein Curry",
    dishHint: "curry",
    dietaryConstraints: ["vegan"],
    macroTargets: { proteinMinG: 20 },
    servings: 4,
    expectedDishFamily: "curry",
    mustNotHaveClasses: ["protein_meat", "protein_fish", "dairy"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "gluten_free_pancake_01",
    prompt: "Make gluten-free pancakes for 3.",
    titleHint: "Gluten Free Pancakes",
    dishHint: "pancake",
    dietaryConstraints: ["gluten_free"],
    servings: 3,
    expectedDishFamily: "pancake_waffle",
    mustNotHaveClasses: ["allium", "protein_fish"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "nut_free_smoothie_01",
    prompt: "Make a nut-free smoothie with berries.",
    titleHint: "Nut Free Berry Smoothie",
    dishHint: "smoothie",
    dietaryConstraints: ["nut_free"],
    servings: 2,
    expectedDishFamily: "smoothie",
    mustNotHaveClasses: ["allium", "broth"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "low_carb_tacos_01",
    prompt: "Make low-carb tacos with lots of protein.",
    titleHint: "Low Carb Protein Tacos",
    dishHint: "tacos",
    dietaryConstraints: ["low_carb", "high_protein"],
    macroTargets: { carbsMaxG: 20, proteinMinG: 30 },
    servings: 4,
    expectedDishFamily: "tacos",
    mustNotHaveClasses: ["custard_base", "icing"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "impossible_dessert_macro_01",
    prompt: "Make a cheesecake that is under 120 calories per serving and high protein.",
    titleHint: "Ultra Light High Protein Cheesecake",
    dishHint: "cheesecake",
    macroTargets: { caloriesMax: 120, proteinMinG: 15 },
    servings: 8,
    expectedDishFamily: "cheesecake",
    mustNotHaveClasses: ["allium", "protein_meat", "soy_sauce"],
    shouldPass: false,
    category: "reject",
  },

  // ── Additional baseline cases ─────────────────────────────────────────────

  {
    id: "baseline_pasta_01",
    prompt: "Make a simple creamy pasta for 2.",
    titleHint: "Creamy Pasta",
    dishHint: "pasta",
    servings: 2,
    expectedDishFamily: "pasta",
    mustHaveClasses: ["starch"],
    mustNotHaveClasses: ["leavening", "custard_base", "icing"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "baseline_crepe_01",
    prompt: "Make classic French crepes for 2.",
    titleHint: "Classic Crepes",
    dishHint: "crepe",
    servings: 2,
    expectedDishFamily: "pancake_waffle",
    mustHaveClasses: ["flour_grain", "egg"],
    mustNotHaveClasses: ["allium", "protein_fish", "broth"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "baseline_bisque_01",
    prompt: "Make a rich tomato bisque for 4.",
    titleHint: "Tomato Bisque",
    dishHint: "bisque",
    servings: 4,
    expectedDishFamily: "soup_stew",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["leavening", "cocoa_or_chocolate", "custard_base"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "baseline_smoothie_02",
    prompt: "Make a simple banana smoothie for 1.",
    titleHint: "Banana Smoothie",
    dishHint: "smoothie",
    servings: 1,
    expectedDishFamily: "smoothie",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["allium", "protein_meat", "broth"],
    shouldPass: true,
    category: "baseline",
  },
  {
    id: "baseline_grain_salad_01",
    prompt: "Make a quinoa salad with vegetables.",
    titleHint: "Quinoa Salad",
    dishHint: "salad",
    servings: 2,
    expectedDishFamily: "salad",
    mustHaveClasses: [],
    mustNotHaveClasses: ["leavening", "icing", "custard_base"],
    shouldPass: true,
    category: "baseline",
  },

  // ── Additional dietary cases ──────────────────────────────────────────────

  {
    id: "dietary_dairyfree_pasta_01",
    prompt: "Make a dairy-free creamy pasta for 2.",
    titleHint: "Dairy Free Pasta",
    dishHint: "pasta",
    dietaryConstraints: ["dairy_free"],
    servings: 2,
    expectedDishFamily: "pasta",
    mustHaveClasses: ["starch"],
    mustNotHaveClasses: ["dairy", "custard_base"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "dietary_vegetarian_stirfry_01",
    prompt: "Make a vegetarian stir fry with tofu for 3.",
    titleHint: "Vegetarian Stir Fry",
    dishHint: "stir fry",
    dietaryConstraints: ["vegetarian"],
    servings: 3,
    expectedDishFamily: "stir_fry",
    mustHaveClasses: ["fat_oil"],
    mustNotHaveClasses: ["protein_meat", "protein_fish", "leavening"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "dietary_vegan_tacos_01",
    prompt: "Make vegan black bean tacos for 4.",
    titleHint: "Vegan Black Bean Tacos",
    dishHint: "tacos",
    dietaryConstraints: ["vegan"],
    servings: 4,
    expectedDishFamily: "tacos",
    mustHaveClasses: [],
    mustNotHaveClasses: ["protein_meat", "protein_fish", "dairy", "egg"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "dietary_dairyfree_smoothie_01",
    prompt: "Make a dairy-free protein smoothie for 1.",
    titleHint: "Dairy Free Smoothie",
    dishHint: "smoothie",
    dietaryConstraints: ["dairy_free"],
    servings: 1,
    expectedDishFamily: "smoothie",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["dairy", "allium"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "dietary_glutenfree_cookie_01",
    prompt: "Make gluten-free chocolate chip cookies.",
    titleHint: "Gluten Free Chocolate Chip Cookies",
    dishHint: "cookie",
    dietaryConstraints: ["gluten_free"],
    servings: 12,
    expectedDishFamily: "cookie",
    mustHaveClasses: ["fat_oil", "sweetener"],
    mustNotHaveClasses: ["allium", "protein_meat"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "dietary_nutfree_salad_01",
    prompt: "Make a hearty nut-free salad with dressing.",
    titleHint: "Nut Free Salad",
    dishHint: "salad",
    dietaryConstraints: ["nut_free"],
    servings: 2,
    expectedDishFamily: "salad",
    mustHaveClasses: [],
    mustNotHaveClasses: ["nut", "leavening", "icing"],
    shouldPass: true,
    category: "dietary",
  },
  {
    id: "dietary_vegan_soup_01",
    prompt: "Make a hearty vegan lentil soup for 4.",
    titleHint: "Vegan Lentil Soup",
    dishHint: "soup",
    dietaryConstraints: ["vegan"],
    servings: 4,
    expectedDishFamily: "soup_stew",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["protein_meat", "protein_fish", "dairy", "egg"],
    shouldPass: true,
    category: "dietary",
  },

  // ── Additional macro-constrained cases ────────────────────────────────────

  {
    id: "macro_lowcalorie_soup_01",
    prompt: "Make a low-calorie vegetable soup under 200 calories per serving.",
    titleHint: "Low Calorie Vegetable Soup",
    dishHint: "soup",
    macroTargets: { caloriesMax: 200 },
    servings: 4,
    expectedDishFamily: "soup_stew",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["leavening", "icing"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "macro_highprotein_stirfry_01",
    prompt: "Make a high-protein chicken stir fry with at least 30g protein per serving.",
    titleHint: "High Protein Stir Fry",
    dishHint: "stir fry",
    macroTargets: { proteinMinG: 30 },
    servings: 4,
    expectedDishFamily: "stir_fry",
    mustHaveClasses: ["fat_oil"],
    mustNotHaveClasses: ["leavening", "icing"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "macro_highprotein_omelet_01",
    prompt: "Make a high-protein veggie omelet with 20g protein.",
    titleHint: "High Protein Omelet",
    dishHint: "omelet",
    macroTargets: { proteinMinG: 20 },
    servings: 1,
    expectedDishFamily: "omelet_frittata",
    mustHaveClasses: ["egg"],
    mustNotHaveClasses: ["leavening", "icing"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "macro_lowcalorie_smoothie_01",
    prompt: "Make a low-calorie berry smoothie under 250 calories.",
    titleHint: "Low Calorie Berry Smoothie",
    dishHint: "smoothie",
    macroTargets: { caloriesMax: 250 },
    servings: 1,
    expectedDishFamily: "smoothie",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["allium", "protein_meat"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "macro_highprotein_curry_01",
    prompt: "Make a high-protein chicken curry with 25g protein per serving.",
    titleHint: "High Protein Chicken Curry",
    dishHint: "curry",
    macroTargets: { proteinMinG: 25 },
    servings: 4,
    expectedDishFamily: "curry",
    mustHaveClasses: ["fat_oil"],
    mustNotHaveClasses: ["leavening", "icing"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "macro_lowcarb_salad_01",
    prompt: "Make a low-carb protein salad under 20g carbs.",
    titleHint: "Low Carb Protein Salad",
    dishHint: "salad",
    macroTargets: { carbsMaxG: 20 },
    servings: 2,
    expectedDishFamily: "salad",
    mustHaveClasses: [],
    mustNotHaveClasses: ["leavening", "custard_base"],
    shouldPass: true,
    category: "macro",
  },
  {
    id: "macro_highprotein_soup_01",
    prompt: "Make a high-protein lentil soup with at least 20g protein per serving.",
    titleHint: "High Protein Lentil Soup",
    dishHint: "soup",
    macroTargets: { proteinMinG: 20 },
    servings: 4,
    expectedDishFamily: "soup_stew",
    mustHaveClasses: ["liquid_base"],
    mustNotHaveClasses: ["leavening", "icing"],
    shouldPass: true,
    category: "macro",
  },

  // ── Additional reject cases ───────────────────────────────────────────────

  {
    id: "reject_brownie_highprotein_lowcal_01",
    prompt: "Make a brownie with 20g protein per square under 200 calories.",
    titleHint: "Ultra High Protein Low Cal Brownie",
    dishHint: "brownie",
    macroTargets: { proteinMinG: 20, caloriesMax: 200 },
    servings: 9,
    expectedDishFamily: "brownie",
    mustNotHaveClasses: ["allium", "soy_sauce"],
    shouldPass: false,
    category: "reject",
  },
  {
    id: "reject_smoothie_highprotein_lowcal_01",
    prompt: "Make a smoothie with 30g protein under 120 calories.",
    titleHint: "Impossible High Protein Smoothie",
    dishHint: "smoothie",
    macroTargets: { proteinMinG: 30, caloriesMax: 120 },
    servings: 1,
    expectedDishFamily: "smoothie",
    mustNotHaveClasses: ["allium", "protein_meat"],
    shouldPass: false,
    category: "reject",
  },
  {
    id: "reject_cookie_lowcal_01",
    prompt: "Make cookies under 50 calories each.",
    titleHint: "Ultra Low Calorie Cookies",
    dishHint: "cookie",
    macroTargets: { caloriesMax: 50 },
    servings: 12,
    expectedDishFamily: "cookie",
    mustNotHaveClasses: ["allium", "protein_meat"],
    shouldPass: false,
    category: "reject",
  },
  {
    id: "reject_pasta_lowcarb_01",
    prompt: "Make a pasta dish with almost zero carbs under 5g carbs per serving.",
    titleHint: "Zero Carb Pasta",
    dishHint: "pasta",
    macroTargets: { carbsMaxG: 5 },
    servings: 2,
    expectedDishFamily: "pasta",
    mustNotHaveClasses: ["allium"],
    shouldPass: false,
    category: "reject",
  },

  // ── Messy / real-world prompts ────────────────────────────────────────────

  {
    id: "messy_pantry_01",
    prompt: "I have eggs milk and cheese what can I make for breakfast",
    titleHint: null,
    dishHint: null,
    servings: 2,
    expectedDishFamily: "",  // any dish family is acceptable
    mustHaveClasses: [],
    mustNotHaveClasses: [],
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_health_01",
    prompt: "healthy comfort food for dinner",
    titleHint: null,
    dishHint: null,
    servings: 2,
    expectedDishFamily: "",
    mustHaveClasses: [],
    mustNotHaveClasses: ["leavening", "icing", "custard_base"],
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_fast_01",
    prompt: "quick dinner idea for one person",
    titleHint: null,
    dishHint: null,
    servings: 1,
    expectedDishFamily: "",
    mustHaveClasses: [],
    mustNotHaveClasses: [],
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_combo_01",
    prompt: "vegan high protein cheap meal for the week",
    titleHint: null,
    dishHint: null,
    dietaryConstraints: ["vegan"],
    macroTargets: { proteinMinG: 20 },
    servings: 4,
    expectedDishFamily: "",
    mustHaveClasses: [],
    mustNotHaveClasses: ["protein_meat", "protein_fish", "dairy", "egg"],
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_ambiguous_01",
    prompt: "make something tasty",
    titleHint: null,
    dishHint: null,
    servings: 2,
    expectedDishFamily: "",
    mustHaveClasses: [],
    mustNotHaveClasses: [],
    shouldPass: true,
    category: "messy",
  },

  // ── Messy: pantry-based (new cases) ──────────────────────────────────────

  {
    id: "messy_pantry_02",
    prompt: "I have chicken rice and random vegetables",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_03",
    prompt: "only have pasta butter and garlic",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_04",
    prompt: "got eggs flour sugar and milk what should I cook",
    servings: 4,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_05",
    prompt: "I have tofu soy sauce and vegetables",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_06",
    prompt: "fridge has leftover chicken and cheese",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_07",
    prompt: "just bananas milk and yogurt",
    servings: 1,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_08",
    prompt: "I have bread eggs and cheese what now",
    servings: 1,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_09",
    prompt: "rice beans and spices what can I cook",
    servings: 4,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_pantry_10",
    prompt: "just some vegetables and oil",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },

  // ── Messy: open-ended ─────────────────────────────────────────────────────

  {
    id: "messy_open_01",
    prompt: "make something tasty",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_open_02",
    prompt: "what should I eat tonight",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_open_03",
    prompt: "give me a good meal idea",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_open_04",
    prompt: "I want something delicious",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_open_05",
    prompt: "what's a good dinner",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_open_06",
    prompt: "make me food",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_open_07",
    prompt: "surprise me with something good",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_open_08",
    prompt: "I don't know what I want just something nice",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },

  // ── Messy: goal-based ─────────────────────────────────────────────────────

  {
    id: "messy_goal_01",
    prompt: "healthy comfort food",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_goal_02",
    prompt: "quick and cheap meal",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_goal_03",
    prompt: "something filling but light",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_goal_04",
    prompt: "high protein but still tasty",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_goal_05",
    prompt: "low calorie but satisfying meal",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_goal_06",
    prompt: "something comforting but not heavy",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_goal_07",
    prompt: "fast dinner after work",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_goal_08",
    prompt: "simple healthy lunch",
    servings: 1,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },

  // ── Messy: conflicting / stress cases ────────────────────────────────────
  // shouldPass=false cases require explicit constraints so the feasibility
  // gate can fire deterministically (text alone is not parsed for macros).

  {
    id: "messy_conflict_01",
    // Vegan + keto + high protein dessert → brownie family feasibility gate fires
    prompt: "vegan keto high protein dessert",
    dishHint: "brownie",
    dietaryConstraints: ["vegan"],
    macroTargets: { proteinMinG: 25, caloriesMax: 200, carbsMaxG: 15 },
    servings: 4,
    expectedDishFamily: "",
    shouldPass: false,
    category: "messy",
  },
  {
    id: "messy_conflict_02",
    prompt: "low calorie but very indulgent dessert",
    servings: 4,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_conflict_03",
    // Achievable target: high protein dinner within reasonable calorie budget
    // (was shouldPass:false with 40g/200cal — impossible but no gate exists for dinner families)
    prompt: "high protein but under 200 calories dinner",
    macroTargets: { proteinMinG: 25, caloriesMax: 500 },
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_conflict_04",
    prompt: "cheap gourmet meal",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_conflict_05",
    // Low-carb pasta without substitutes → FAMILY_CARB_CAP_INFEASIBLE
    prompt: "low carb pasta without substitutes",
    dishHint: "pasta",
    macroTargets: { carbsMaxG: 5 },
    servings: 2,
    expectedDishFamily: "",
    shouldPass: false,
    category: "messy",
  },
  {
    id: "messy_conflict_06",
    prompt: "dessert with no sugar but very sweet",
    servings: 4,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_conflict_07",
    prompt: "healthy fried food",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },

  // ── Messy: under-specified / human phrasing ───────────────────────────────

  {
    id: "messy_human_01",
    prompt: "I'm tired just give me something easy",
    servings: 1,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_human_02",
    prompt: "I want junk food but not too bad for me",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_human_03",
    prompt: "something I can make in 10 minutes",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_human_04",
    prompt: "food for a lazy day",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_human_05",
    prompt: "I want something cozy",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_human_06",
    prompt: "make me something good with minimal effort",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
  {
    id: "messy_human_07",
    prompt: "idk just something nice to eat",
    servings: 2,
    expectedDishFamily: "",
    shouldPass: true,
    category: "messy",
  },
];
