// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/accounts" | "/admin/ai" | "/admin/logs" | "/admin/usage" | "/cook/live/[share_slug]" | "/dashboard" | "/debug/ai" | "/debug/stock-covers" | "/import" | "/login" | "/my-recipes" | "/new-recipe" | "/planner" | "/preferences" | "/pricing" | "/recipe/[id]" | "/recipes" | "/recipes/[id]" | "/recipes/[id]/new-version" | "/recipes/[id]/versions/[versionId]" | "/recipes/[id]/versions/[versionId]/cook" | "/recipes/[id]/versions/[versionId]/grocery" | "/recipes/[id]/versions/new" | "/recipes/new" | "/recipes/new/from-text" | "/settings" | "/sign-in" | "/sign-up"
type AppRouteHandlerRoutes = "/api/admin/ai-model-test" | "/api/admin/ai-task-settings" | "/api/admin/feature-flags" | "/api/ai/chef-chat" | "/api/ai/home" | "/api/ai/home/build" | "/api/ai/improve-recipe" | "/api/ai/nutrition" | "/api/ai/structure-recipe" | "/api/chef-fix/apply" | "/api/chef-fix/generate" | "/api/chef-fix/preview" | "/api/chef-rules/apply" | "/api/chef-rules/debug" | "/api/chef-score/calculate" | "/api/chef-score/compare" | "/api/chef-score/recalculate" | "/api/planner/week" | "/api/recipes" | "/api/recipes/[id]" | "/api/recipes/[id]/versions" | "/api/recipes/[id]/versions/[versionId]" | "/api/recipes/[id]/versions/[versionId]/grocery" | "/api/recipes/[id]/versions/[versionId]/live" | "/api/recipes/[id]/versions/[versionId]/photos" | "/api/recipes/[id]/versions/[versionId]/prep-progress" | "/api/recipes/[id]/visibility" | "/api/recipes/browse" | "/api/recipes/sidebar" | "/api/taste/feedback" | "/api/taste/scores" | "/api/taste/why-fits" | "/api/user/preferences/pantry" | "/apple-touch-icon-precomposed.png"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/accounts": {}
  "/admin/ai": {}
  "/admin/logs": {}
  "/admin/usage": {}
  "/api/admin/ai-model-test": {}
  "/api/admin/ai-task-settings": {}
  "/api/admin/feature-flags": {}
  "/api/ai/chef-chat": {}
  "/api/ai/home": {}
  "/api/ai/home/build": {}
  "/api/ai/improve-recipe": {}
  "/api/ai/nutrition": {}
  "/api/ai/structure-recipe": {}
  "/api/chef-fix/apply": {}
  "/api/chef-fix/generate": {}
  "/api/chef-fix/preview": {}
  "/api/chef-rules/apply": {}
  "/api/chef-rules/debug": {}
  "/api/chef-score/calculate": {}
  "/api/chef-score/compare": {}
  "/api/chef-score/recalculate": {}
  "/api/planner/week": {}
  "/api/recipes": {}
  "/api/recipes/[id]": { "id": string; }
  "/api/recipes/[id]/versions": { "id": string; }
  "/api/recipes/[id]/versions/[versionId]": { "id": string; "versionId": string; }
  "/api/recipes/[id]/versions/[versionId]/grocery": { "id": string; "versionId": string; }
  "/api/recipes/[id]/versions/[versionId]/live": { "id": string; "versionId": string; }
  "/api/recipes/[id]/versions/[versionId]/photos": { "id": string; "versionId": string; }
  "/api/recipes/[id]/versions/[versionId]/prep-progress": { "id": string; "versionId": string; }
  "/api/recipes/[id]/visibility": { "id": string; }
  "/api/recipes/browse": {}
  "/api/recipes/sidebar": {}
  "/api/taste/feedback": {}
  "/api/taste/scores": {}
  "/api/taste/why-fits": {}
  "/api/user/preferences/pantry": {}
  "/apple-touch-icon-precomposed.png": {}
  "/cook/live/[share_slug]": { "share_slug": string; }
  "/dashboard": {}
  "/debug/ai": {}
  "/debug/stock-covers": {}
  "/import": {}
  "/login": {}
  "/my-recipes": {}
  "/new-recipe": {}
  "/planner": {}
  "/preferences": {}
  "/pricing": {}
  "/recipe/[id]": { "id": string; }
  "/recipes": {}
  "/recipes/[id]": { "id": string; }
  "/recipes/[id]/new-version": { "id": string; }
  "/recipes/[id]/versions/[versionId]": { "id": string; "versionId": string; }
  "/recipes/[id]/versions/[versionId]/cook": { "id": string; "versionId": string; }
  "/recipes/[id]/versions/[versionId]/grocery": { "id": string; "versionId": string; }
  "/recipes/[id]/versions/new": { "id": string; }
  "/recipes/new": {}
  "/recipes/new/from-text": {}
  "/settings": {}
  "/sign-in": {}
  "/sign-up": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
