// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/accounts">> = Specific
  const handler = {} as typeof import("../../../app/admin/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ai">> = Specific
  const handler = {} as typeof import("../../../app/admin/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../../app/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/usage">> = Specific
  const handler = {} as typeof import("../../../app/admin/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cook/live/[share_slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cook/live/[share_slug]">> = Specific
  const handler = {} as typeof import("../../../app/cook/live/[share_slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/debug/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug/ai">> = Specific
  const handler = {} as typeof import("../../../app/debug/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/debug/stock-covers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug/stock-covers">> = Specific
  const handler = {} as typeof import("../../../app/debug/stock-covers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import">> = Specific
  const handler = {} as typeof import("../../../app/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my-recipes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-recipes">> = Specific
  const handler = {} as typeof import("../../../app/my-recipes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/new-recipe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-recipe">> = Specific
  const handler = {} as typeof import("../../../app/new-recipe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planner">> = Specific
  const handler = {} as typeof import("../../../app/planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preferences">> = Specific
  const handler = {} as typeof import("../../../app/preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipe/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipe/[id]">> = Specific
  const handler = {} as typeof import("../../../app/recipe/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/[id]/new-version/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/new-version">> = Specific
  const handler = {} as typeof import("../../../app/recipes/[id]/new-version/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]">> = Specific
  const handler = {} as typeof import("../../../app/recipes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/[id]/versions/[versionId]/cook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/[versionId]/cook">> = Specific
  const handler = {} as typeof import("../../../app/recipes/[id]/versions/[versionId]/cook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/[id]/versions/[versionId]/grocery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/[versionId]/grocery">> = Specific
  const handler = {} as typeof import("../../../app/recipes/[id]/versions/[versionId]/grocery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/[id]/versions/[versionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../../app/recipes/[id]/versions/[versionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/[id]/versions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/[id]/versions/new">> = Specific
  const handler = {} as typeof import("../../../app/recipes/[id]/versions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/new/from-text/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/new/from-text">> = Specific
  const handler = {} as typeof import("../../../app/recipes/new/from-text/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes/new">> = Specific
  const handler = {} as typeof import("../../../app/recipes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recipes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes">> = Specific
  const handler = {} as typeof import("../../../app/recipes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../../app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../../app/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ai-model-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ai-model-test">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ai-model-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ai-task-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ai-task-settings">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ai-task-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/feature-flags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/feature-flags">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/feature-flags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/chef-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chef-chat">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/chef-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/home/build/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/home/build">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/home/build/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/home/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/home">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/home/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/improve-recipe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/improve-recipe">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/improve-recipe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/nutrition/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/nutrition">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/nutrition/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/structure-recipe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/structure-recipe">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/structure-recipe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-fix/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-fix/apply">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-fix/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-fix/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-fix/generate">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-fix/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-fix/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-fix/preview">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-fix/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-rules/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-rules/apply">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-rules/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-rules/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-rules/debug">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-rules/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-score/calculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-score/calculate">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-score/calculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-score/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-score/compare">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-score/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chef-score/recalculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chef-score/recalculate">> = Specific
  const handler = {} as typeof import("../../../app/api/chef-score/recalculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/planner/week/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/week">> = Specific
  const handler = {} as typeof import("../../../app/api/planner/week/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/versions/[versionId]/grocery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/versions/[versionId]/grocery">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/versions/[versionId]/grocery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/versions/[versionId]/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/versions/[versionId]/live">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/versions/[versionId]/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/versions/[versionId]/photos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/versions/[versionId]/photos">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/versions/[versionId]/photos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/versions/[versionId]/prep-progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/versions/[versionId]/prep-progress">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/versions/[versionId]/prep-progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/versions/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/versions/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/versions">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/[id]/visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/[id]/visibility">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/[id]/visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/browse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/browse">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/browse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recipes/sidebar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recipes/sidebar">> = Specific
  const handler = {} as typeof import("../../../app/api/recipes/sidebar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/taste/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taste/feedback">> = Specific
  const handler = {} as typeof import("../../../app/api/taste/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/taste/scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taste/scores">> = Specific
  const handler = {} as typeof import("../../../app/api/taste/scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/taste/why-fits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taste/why-fits">> = Specific
  const handler = {} as typeof import("../../../app/api/taste/why-fits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/preferences/pantry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/preferences/pantry">> = Specific
  const handler = {} as typeof import("../../../app/api/user/preferences/pantry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/apple-touch-icon-precomposed.png/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/apple-touch-icon-precomposed.png">> = Specific
  const handler = {} as typeof import("../../../app/apple-touch-icon-precomposed.png/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
