var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/structure-recipe/route.js")
R.c("server/chunks/[root-of-the-server]__f80b3f61._.js")
R.c("server/chunks/[root-of-the-server]__53777ab9._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_35494b11.js")
R.c("server/chunks/_08811d08._.js")
R.c("server/chunks/node_modules_zod_v4_58d952c2._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_structure-recipe_route_actions_beb2127c.js")
R.m(54968)
module.exports=R.m(54968).exports
