import type { RescueScenario } from "./rescueScenarios";

// ---------------------------------------------------------------------------
// Supporting enums / union types
// ---------------------------------------------------------------------------

export type GuidanceImportance = "critical" | "important" | "nice_to_know";

export type StepLinkage = {
  /** Zero-based index into RecipeDraft.steps */
  stepIndex: number;
  /** Human-readable step excerpt for debugging / display */
  stepText?: string;
};

// ---------------------------------------------------------------------------
// Core coaching elements
// ---------------------------------------------------------------------------

/**
 * A chef-level insight that elevates the dish — technique, timing, or sensory
 * signal that home cooks typically miss.
 */
export type ChefSecret = {
  text: string;
  rationale: string;
  stepLinkage?: StepLinkage;
};

/**
 * A sensory or visual cue the cook should watch for during cooking.
 */
export type WatchFor = {
  cue: string;
  importance: GuidanceImportance;
  stepLinkage?: StepLinkage;
};

/**
 * A common mistake and how to prevent it before it happens.
 */
export type MistakePrevention = {
  mistake: string;
  prevention: string;
  importance: GuidanceImportance;
};

/**
 * An in-session rescue move for a specific failure scenario.
 * These are for saving the current dish — not for improving future versions.
 */
export type RecoveryMove = {
  scenario: RescueScenario;
  move: string;
  /** True when the move is tailored to the dish family rather than generic */
  familyAware: boolean;
};

// ---------------------------------------------------------------------------
// Top-level coaching contract
// ---------------------------------------------------------------------------

/**
 * CookingCoach owns actionable pre-cook guidance, step-linked cues,
 * mistake prevention, and in-session recovery moves for migrated recipes.
 *
 * Authority: see docs/decisions/m3-authority-boundaries.md
 * Generated by: lib/ai/coaching/buildCookingCoach.ts (rule-based, no LLM call)
 */
export type CookingCoach = {
  /** 1–2 chef-level insights that make the most difference */
  chefSecrets: ChefSecret[];
  /** Key sensory/visual cues to watch during cooking */
  watchFors: WatchFor[];
  /** Common mistakes and how to prevent them */
  mistakePreviews: MistakePrevention[];
  /** In-session recovery moves for likely failure scenarios */
  recoveryMoves: RecoveryMove[];
  /** requestId from ResolvedCookingIntent */
  generatedFrom: string;
  generatedAt: string;
};
