insert into public.chef_rules (
  id,
  rule_key,
  title,
  category,
  subcategory,
  layer,
  trigger_conditions,
  exclusion_conditions,
  rule_type,
  severity,
  user_explanation,
  failure_if_missing,
  action_type,
  action_payload_template,
  expected_score_impact,
  confidence,
  applicability,
  priority
) values
('chef-rule-1', 'taste_as_you_cook', 'Taste as you cook', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Taste as you cook so seasoning and balance stay under control.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-2', 'season_in_layers', 'Season in layers', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Season in layers instead of dumping all the salt in at the end.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-3', 'mise_en_place', 'Mise en place', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Prep your ingredients before heat is involved so timing stays manageable.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-4', 'sharp_knives_matter', 'Sharp knives matter', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A sharp knife gives cleaner cuts, faster prep, and more even cooking.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-5', 'do_not_overcrowd_searing_surfaces', 'Do not overcrowd searing surfaces', 'universal', NULL, 'foundation', '{"usesSearMethod":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Do not overcrowd the pan or you will steam instead of brown.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-6', 'let_food_release_naturally', 'Let food release naturally', 'universal', NULL, 'foundation', '{"usesSearMethod":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Let the surface release naturally before flipping so browning can develop.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-7', 'control_heat', 'Control heat', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Control the heat instead of defaulting to high.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-8', 'fix_flat_flavor_with_acid', 'Fix flat flavor with acid', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'If a dish tastes flat, acid is often the fastest way to wake it up.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-9', 'salt_is_structure', 'Salt is structure', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Salt should build flavor, not just make the final bite salty.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-10', 'rest_proteins', 'Rest proteins', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Rest cooked proteins before slicing so juices redistribute.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-11', 'dry_before_searing', 'Dry before searing', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Dry the surface before searing so you can brown instead of steam.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-12', 'preheat_cookware', 'Preheat cookware', 'universal', NULL, 'foundation', '{"usesSauteMethod":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Preheat the pan before adding food so color develops quickly.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-13', 'match_oil_to_heat', 'Match oil to heat', 'universal', NULL, 'foundation', '{"usesHighHeat":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Use a fat with the right smoke point for the heat level.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-14', 'too_many_ingredients_can_blur_the_dish', 'Too many ingredients can blur the dish', 'universal', NULL, 'foundation', '{"hasHighIngredientCount":true}'::jsonb, '{}'::jsonb, 'warning', 'high', 'If too many ingredients compete, the dish can lose focus.', NULL, NULL, NULL, 4, 0.85, 'conditional', 4),
('chef-rule-15', 'clean_as_you_go', 'Clean as you go', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Clean as you go so the cook stays calm and organized.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-16', 'read_the_recipe_first', 'Read the recipe first', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Read the full recipe before you start cooking.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-17', 'final_seasoning_matters', 'Final seasoning matters', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Check seasoning at the end after reduction and carryover change the flavor.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-18', 'rest_dough_when_possible', 'Rest dough when possible', 'baking', NULL, 'technique', '{"isDough":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Resting dough improves hydration and structure.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-19', 'temperature_beats_time', 'Temperature beats time', 'universal', NULL, 'foundation', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Temperature and sensory cues matter more than the clock alone.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-20', 'use_a_thermometer_when_needed', 'Use a thermometer when needed', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A thermometer removes guesswork from protein cooking.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-21', 'bake_by_weight_when_possible', 'Bake by weight when possible', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Measure baking ingredients precisely, ideally by weight.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-22', 'preheat_the_oven_fully', 'Preheat the oven fully', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Do not start baking before the oven is fully preheated.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-23', 'avoid_overmixing', 'Avoid overmixing', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Mix only until combined unless the method clearly calls for more.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-24', 'chill_cookie_dough', 'Chill cookie dough', 'baking', 'cookies', 'technique', '{"isCookies":true}'::jsonb, '{"isSourdough":true,"isNonDairyBaking":true}'::jsonb, 'recommended', 'medium', 'Chill cookie dough before baking for better texture and less spread.', NULL, 'add_step', '{"content":"Refrigerate the dough for 30 to 60 minutes before baking."}'::jsonb, 3, 0.85, 'conditional', 2),
('chef-rule-25', 'room_temperature_ingredients', 'Room-temperature ingredients', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Room-temperature ingredients combine more evenly in many batters and doughs.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-26', 'correct_pan_size', 'Correct pan size', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Use the intended pan size so time and texture stay predictable.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-27', 'rotate_pans', 'Rotate pans', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Rotate pans if your oven browns unevenly.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-28', 'do_not_open_the_oven_early', 'Do not open the oven early', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Avoid opening the oven too early or fragile bakes can collapse.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-29', 'sift_when_needed', 'Sift when needed', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Sift dry ingredients when clumping or delicate texture matters.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-30', 'weigh_flour', 'Weigh flour', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Weigh flour instead of scooping it when accuracy matters.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-31', 'know_hot_spots', 'Know hot spots', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Know your oven''s hot spots and rotate if needed.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-32', 'use_parchment', 'Use parchment', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Parchment improves release and makes browning more consistent.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-33', 'bake_for_color_not_just_time', 'Bake for color, not just time', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Use color and structure cues, not only minutes, to judge doneness.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-34', 'one_variable_at_a_time', 'One variable at a time', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'warning', 'high', 'Changing too many baking variables at once makes failures hard to diagnose.', NULL, NULL, NULL, 4, 0.85, 'conditional', 4),
('chef-rule-35', 'cool_properly', 'Cool properly', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Cooling is part of the bake because structure continues to set.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-36', 'salt_supports_sweetness', 'Salt supports sweetness', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Salt sharpens sweetness and prevents desserts from tasting flat.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-37', 'fresh_leaveners', 'Fresh leaveners', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Old baking soda and baking powder quietly ruin results.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-38', 'do_not_overbake', 'Do not overbake', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Pull baked goods when they are done, not when they look dried out.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-39', 'hydration_shapes_texture', 'Hydration shapes texture', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Hydration changes chew, spread, and crumb more than many cooks expect.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-40', 'gluten_develops_with_rest', 'Gluten develops with rest', 'baking', NULL, 'technique', '{"isDough":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Resting dough helps gluten and hydration settle.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-41', 'fat_temperature_matters', 'Fat temperature matters', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'The state of the fat changes spread, aeration, and tenderness.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-42', 'cream_butter_and_sugar_correctly', 'Cream butter and sugar correctly', 'baking', NULL, 'technique', '{"usesCreamingMethod":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Cream butter and sugar long enough to build structure.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-43', 'avoid_blind_substitutions', 'Avoid blind substitutions', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'warning', 'high', 'Substitutions in baking need method and ratio awareness.', NULL, NULL, NULL, 4, 0.85, 'conditional', 4),
('chef-rule-44', 'internal_cues_decide_doneness', 'Internal cues decide doneness', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Look for structure, color, and texture cues before trusting time.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-45', 'ratios_are_chemistry', 'Ratios are chemistry', 'baking', NULL, 'technique', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Baking works because ratios hold together.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-46', 'temper_proteins_before_cooking', 'Temper proteins before cooking', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Taking the chill off protein can help it cook more evenly.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-47', 'pat_meat_dry', 'Pat meat dry', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Pat protein dry before high heat for better browning.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-48', 'do_not_move_meat_too_early', 'Do not move meat too early', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Let browning happen before you start moving meat around.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-49', 'sear_then_manage_heat', 'Sear then manage heat', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Use strong initial heat for color, then lower it if needed to finish gently.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-50', 'rest_before_slicing', 'Rest before slicing', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Rest before slicing so juices stay in the meat.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-51', 'slice_against_the_grain', 'Slice against the grain', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Slice against the grain when tenderness matters.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-52', 'thermometer_beats_guessing', 'Thermometer beats guessing', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Use a thermometer instead of guessing doneness.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-53', 'season_early', 'Season early', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Season protein before cooking so the surface is not bland.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-54', 'do_not_crowd_browning_pans', 'Do not crowd browning pans', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Crowding the pan kills the sear.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-55', 'use_carryover_cooking', 'Use carryover cooking', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Carryover heat keeps cooking after the pan or oven is gone.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-56', 'fat_carries_flavor', 'Fat carries flavor', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A little fat often carries flavor and improves perception of juiciness.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-57', 'marinate_tougher_cuts', 'Marinate tougher cuts', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Use marinades or brines when the cut needs help.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-58', 'low_and_slow_for_tough_cuts', 'Low and slow for tough cuts', 'protein', NULL, 'technique', '{"isToughCut":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Tough cuts need time to soften.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-59', 'protect_lean_meats', 'Protect lean meats', 'protein', NULL, 'technique', '{"isLeanProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Lean proteins dry out quickly, so stop cooking precisely.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-60', 'chicken_temp_guidance', 'Chicken temp guidance', 'protein', 'chicken', 'technique', '{"isChicken":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Chicken needs explicit internal temperature guidance for safety and texture.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-61', 'dry_skin_crisps', 'Dry skin crisps', 'protein', NULL, 'technique', '{"hasSkinOnProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Dry skin crisps better than damp skin.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-62', 'oil_the_food_for_grilling', 'Oil the food for grilling', 'grilling', NULL, 'technique', '{"isGrilling":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'For grilling, lightly oil the food instead of flooding the grates.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-63', 'rest_redistributes_juices', 'Rest redistributes juices', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Resting gives meat time to reabsorb juices.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-64', 'gentler_cooking_avoids_toughness', 'Gentler cooking avoids toughness', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Lower, steadier heat often prevents toughness.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-65', 'salt_early_for_penetration', 'Salt early for penetration', 'protein', NULL, 'technique', '{"isProtein":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Early salting penetrates better than last-second seasoning.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-66', 'balance_salt_fat_acid_heat', 'Balance salt fat acid heat', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Think in salt, fat, acid, and heat so flavor stays balanced.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-67', 'brighten_with_acid_near_the_end', 'Brighten with acid near the end', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A finishing acid often restores life to a heavy or flat dish.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-68', 'finish_herbs_late', 'Finish herbs late', 'flavor', NULL, 'technique', '{"hasHerbs":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Delicate herbs are brighter when added near the end.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-69', 'toast_spices', 'Toast spices', 'flavor', NULL, 'technique', '{"hasSpices":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Toasting spices deepens aroma and complexity.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-70', 'bloom_spices_in_fat', 'Bloom spices in fat', 'flavor', NULL, 'technique', '{"hasSpices":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Bloom spices in fat so their flavor opens up.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-71', 'sweetness_can_tame_acid', 'Sweetness can tame acid', 'flavor', NULL, 'technique', '{"hasHighAcid":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A touch of sweetness can round off high acid.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-72', 'salt_can_reduce_bitterness', 'Salt can reduce bitterness', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A little salt often softens bitterness.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-73', 'umami_builds_depth', 'Umami builds depth', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Depth often comes from umami rather than more salt alone.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-74', 'layer_flavors', 'Layer flavors', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Layer flavor over time instead of dumping everything in at once.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-75', 'taste_after_major_changes', 'Taste after major changes', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Taste after every major step or seasoning change.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-76', 'reduce_sauces_enough', 'Reduce sauces enough', 'sauce', NULL, 'technique', '{"isSauce":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Sauces need enough reduction to develop body and concentration.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-77', 'fat_carries_flavor_everywhere', 'Fat carries flavor everywhere', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Flavor perception changes when there is enough fat to carry aroma.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-78', 'fresh_ingredients_beat_clutter', 'Fresh ingredients beat clutter', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Freshness matters more than adding extra ingredients.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-79', 'use_texture_contrast', 'Use texture contrast', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Texture contrast makes food feel more complete.', NULL, NULL, NULL, 3, 0.85, 'broad', 2),
('chef-rule-80', 'finish_with_salt_or_acid', 'Finish with salt or acid', 'flavor', NULL, 'technique', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Final salt or acid often separates a finished dish from a dull one.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-81', 'cookie_structure_needs_cold_dough', 'Cookie structure needs cold dough', 'special', 'cookies', 'risk', '{"isCookies":true,"isSourdough":true}'::jsonb, '{}'::jsonb, 'mandatory', 'critical', 'Cookies that are prone to spread should be baked from chilled dough.', 'Cookies spread too thin and lose texture.', 'add_step', '{"content":"Refrigerate the dough for 30 to 60 minutes before baking."}'::jsonb, 5, 0.85, 'conditional', 3),
('chef-rule-82', 'non_dairy_fats_spread_faster', 'Non-dairy fats spread faster', 'special', 'non_dairy_baking', 'risk', '{"isNonDairyBaking":true}'::jsonb, '{}'::jsonb, 'mandatory', 'critical', 'Non-dairy fats melt faster than butter, so cold dough matters more.', 'Cookies spread excessively and bake up greasy or thin.', 'add_note', '{"content":"Non-dairy fats soften quickly, so keep the dough cold and bake on parchment for better structure."}'::jsonb, 5, 0.85, 'conditional', 3),
('chef-rule-83', 'balance_sourdough_acidity', 'Balance sourdough acidity', 'special', 'sourdough', 'risk', '{"isSourdough":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Sourdough discard adds acidity and benefits from deliberate balancing.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-84', 'do_not_boil_low_fat_dairy', 'Do not boil low-fat dairy', 'special', 'dairy', 'risk', '{"usesLowFatDairy":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Low-fat dairy can split when boiled aggressively.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-85', 'starch_stabilizes_sauces', 'Starch stabilizes sauces', 'special', 'sauce', 'risk', '{"isSauce":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Starch can stabilize a sauce that wants to break.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-86', 'finish_pasta_in_sauce', 'Finish pasta in sauce', 'special', 'pasta', 'risk', '{"isPasta":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Finish pasta in the sauce so it emulsifies instead of sitting on top.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-87', 'reserve_pasta_water', 'Reserve pasta water', 'special', 'pasta', 'risk', '{"isPasta":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Pasta water is the easiest tool for emulsifying sauce.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-88', 'do_not_rinse_pasta', 'Do not rinse pasta', 'special', 'pasta', 'risk', '{"isPasta":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Do not rinse pasta unless the dish specifically needs it.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-89', 'preheat_the_grill', 'Preheat the grill', 'special', 'grilling', 'risk', '{"isGrilling":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'A fully preheated grill gives better release and browning.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-90', 'manage_flare_ups', 'Manage flare-ups', 'special', 'grilling', 'risk', '{"isGrilling":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Control flare-ups by managing excess fat and hot spots.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-91', 'use_carryover_in_baking_too', 'Use carryover in baking too', 'special', 'baking', 'risk', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Carryover heat matters in baking, especially with cookies and bars.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-92', 'let_sauces_settle_briefly', 'Let sauces settle briefly', 'special', 'sauce', 'risk', '{"isSauce":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A short rest helps sauces thicken and flavors settle.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-93', 'parchment_improves_consistency', 'Parchment improves consistency', 'special', 'baking', 'risk', '{"isBaking":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Parchment removes a lot of unnecessary baking variance.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-94', 'hydrate_grains_properly', 'Hydrate grains properly', 'special', 'grains', 'risk', '{"isGrains":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'Grains need the right liquid and a proper rest to finish well.', NULL, NULL, NULL, 5, 0.85, 'conditional', 3),
('chef-rule-95', 'rinse_rice_when_appropriate', 'Rinse rice when appropriate', 'special', 'rice', 'risk', '{"isRice":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Rinsing rice can improve final texture when separate grains matter.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-96', 'toast_rice_for_flavor', 'Toast rice for flavor', 'special', 'rice', 'risk', '{"isRice":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Toasting rice before adding liquid adds depth.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-97', 'do_not_stir_risotto_nonstop', 'Do not stir risotto nonstop', 'special', 'risotto', 'risk', '{"isRisotto":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'Constant risotto stirring is less important than steady liquid management.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-98', 'finish_some_sauces_with_butter', 'Finish some sauces with butter', 'special', 'finish', 'risk', '{"isSauce":true}'::jsonb, '{}'::jsonb, 'recommended', 'medium', 'A butter finish can round out texture and shine when the dish allows it.', NULL, NULL, NULL, 3, 0.85, 'conditional', 2),
('chef-rule-99', 'acid_revives_flat_dishes', 'Acid revives flat dishes', 'special', 'flavor_fix', 'risk', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'When a dish tastes flat, try acid before piling on more salt.', NULL, NULL, NULL, 5, 0.85, 'broad', 3),
('chef-rule-100', 'simplicity_wins', 'Simplicity wins', 'special', 'universal', 'risk', '{"always":true}'::jsonb, '{}'::jsonb, 'mandatory', 'high', 'A simpler, coherent dish usually beats a cluttered one.', NULL, NULL, NULL, 5, 0.85, 'broad', 3)
on conflict (rule_key) do update set
  title = excluded.title,
  category = excluded.category,
  subcategory = excluded.subcategory,
  layer = excluded.layer,
  trigger_conditions = excluded.trigger_conditions,
  exclusion_conditions = excluded.exclusion_conditions,
  rule_type = excluded.rule_type,
  severity = excluded.severity,
  user_explanation = excluded.user_explanation,
  failure_if_missing = excluded.failure_if_missing,
  action_type = excluded.action_type,
  action_payload_template = excluded.action_payload_template,
  expected_score_impact = excluded.expected_score_impact,
  confidence = excluded.confidence,
  applicability = excluded.applicability,
  priority = excluded.priority;

insert into public.chef_category_expectations (
  recipe_category,
  expectation_key,
  description,
  bucket,
  impact
) values
('cookies', 'hasBakeTemperature', 'Specify a bake temperature.', 'clarity', -3),
('cookies', 'hasDonenessCue', 'Add a sensory doneness cue for cookies.', 'technique', -4),
('cookies', 'hasCoolingStep', 'Include a cooling step so the cookies finish setting.', 'texture', -3),
('cookies', 'hasChillStep', 'Add a chill step when the dough is spread-prone.', 'technique', -5),
('cookies', 'hasSaltIngredient', 'Salt should be present to support sweetness and structure.', 'flavor', -2),
('cookies', 'hasFatBehaviorGuidance', 'Call out how the fat behaves so texture is predictable.', 'extras', -3),
('chicken', 'hasInternalTempCue', 'Add a specific internal temperature cue.', 'risk', -5),
('chicken', 'hasRestStep', 'Include a rest step before slicing or serving.', 'technique', -4),
('chicken', 'hasDrySurfaceCue', 'Tell the cook to dry the surface before roasting or searing.', 'technique', -3),
('chicken', 'hasSeasoningCue', 'Seasoning should be explicit, not implied.', 'flavor', -2),
('baking', 'hasBakeTemperature', 'Include a specific oven temperature.', 'clarity', -3),
('baking', 'hasCoolingStep', 'Tell the cook how to cool the bake.', 'texture', -3),
('protein', 'hasRestStep', 'Include a rest step to protect texture.', 'technique', -4),
('protein', 'hasInternalTempCue', 'Use internal temperature guidance when relevant.', 'risk', -4)
on conflict (recipe_category, expectation_key) do update set
  description = excluded.description,
  bucket = excluded.bucket,
  impact = excluded.impact;
