// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/cook/live/[share_slug]" | "/dashboard" | "/import" | "/login" | "/my-recipes" | "/new-recipe" | "/preferences" | "/recipe/[id]" | "/recipes" | "/recipes/[id]" | "/recipes/[id]/new-version" | "/recipes/[id]/versions/[versionId]" | "/recipes/[id]/versions/[versionId]/cook" | "/recipes/[id]/versions/[versionId]/grocery" | "/recipes/[id]/versions/new" | "/recipes/new" | "/recipes/new/from-text" | "/sign-in" | "/sign-up"
type AppRouteHandlerRoutes = "/api/ai/chef-chat" | "/api/ai/improve-recipe" | "/api/recipes/[id]/versions/[versionId]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/chef-chat": {}
  "/api/ai/improve-recipe": {}
  "/api/recipes/[id]/versions/[versionId]": { "id": string; "versionId": string; }
  "/cook/live/[share_slug]": { "share_slug": string; }
  "/dashboard": {}
  "/import": {}
  "/login": {}
  "/my-recipes": {}
  "/new-recipe": {}
  "/preferences": {}
  "/recipe/[id]": { "id": string; }
  "/recipes": {}
  "/recipes/[id]": { "id": string; }
  "/recipes/[id]/new-version": { "id": string; }
  "/recipes/[id]/versions/[versionId]": { "id": string; "versionId": string; }
  "/recipes/[id]/versions/[versionId]/cook": { "id": string; "versionId": string; }
  "/recipes/[id]/versions/[versionId]/grocery": { "id": string; "versionId": string; }
  "/recipes/[id]/versions/new": { "id": string; }
  "/recipes/new": {}
  "/recipes/new/from-text": {}
  "/sign-in": {}
  "/sign-up": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
